env:
  es2021: true
  commonjs: true
  node: true

extends:
  - airbnb-base
  - prettier

plugins:
  - prettier

parserOptions:
  ecmaVersion: 12

rules:
  no-return-assign: 0
  no-use-before-define: off
  prefer-arrow-callback: off
  strict:
    - 0
    - global
