openapi: '3.0.0'
info:
  title: 'Core Microservice'
  description: >
    This microservice is part of the **Seedy FIUBA Project**.
  version: '1.0.0'
  contact:
    name: Learn more
    url: 'https://github.com/orgs/SeedyFiuba-G8/'

servers:
  - url: http://sf-tdp2-core-orod.herokuapp.com/
    description: 'Production'
  - url: http://sf-tdp2-core-development.herokuapp.com/
    description: 'Staging'
  - url: http://localhost:3000/
    description: 'Local development'

tags:
  - name: Admin
    description: 'Admin operations'

  - name: User
    description: 'User operations'

  - name: Status

paths:
  /:
    get:
      tags:
        - Documentation
      operationId: docs
      responses:
        200:
          description: 'Description specified.'
  /api-docs:
  get:
    tags:
      - Documentation
    operationId: docs
    responses:
      200:
        description: 'Description specified.'
  # USER ENDPOINTS

  # STATUS
  /ping:
    get:
      tags:
        - Status
      operationId: ping
      responses:
        200:
          description: 'Server is active.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'OK'

  /health:
    get:
      tags:
        - Status
      operationId: health
      responses:
        200:
          description: 'Microservice general health state reported.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  database:
                    type: string
                    example: 'UP'
