openapi: '3.0.0'
info:
  title: 'Core Microservice'
  description: >
    This microservice is part of the **Seedy FIUBA Project**.
  version: '1.0.0'
  contact:
    name: Learn more
    url: 'https://github.com/orgs/SeedyFiuba-G8/'

servers:
  - url: http://sf-tdp2-core-orod.herokuapp.com/
    description: 'Production'
  - url: http://sf-tdp2-core-development.herokuapp.com/
    description: 'Staging'
  - url: http://localhost:3000/
    description: 'Local development'

tags:
  - name: Admin
    description: 'Admin operations'

  - name: User
    description: 'User operations'

  - name: Status

paths:
  /:
    get:
      tags:
        - Documentation
      operationId: docs
      responses:
        200:
          description: 'Description specified.'
  /api-docs:
  get:
    tags:
      - Documentation
    operationId: docs
    responses:
      200:
        description: 'Description specified.'

  # USER ENDPOINTS
  /projects:
    get:
      tags:
        - Project
      operationId: getAllProjects
      summary: 'Get info from all projects'
      responses:
        200:
          description: 'Projects info was retrieved successfully.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  projects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: '670b9562-b30d-52d5-b827-655787665500'
                        title:
                          type: string
                          example: 'Prohibir la utilizacion de Winbugs globalmente'
                        description:
                          type: string
                          example: 'No puede ser que haya gente que use Winbugs'
                        type:
                          type: string
                          example: 'social'
                        objective:
                          type: string
                          example: 'Salvar a la gente de esta maldicion'
                        country:
                          type: string
                          example: 'Argentina'
                        city:
                          type: string
                          example: 'Buenos Aires'
                        published_on:
                          type: string
                          example: '?'
                        finalized_by:
                          type: string
                          example: '?'

        400:
          description: 'Bad request.'
        409:
          description: 'It was not possible to get projects info.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  err:
                    type: string
                    example: 'Id do not match any project.'

  # STATUS
  /ping:
    get:
      tags:
        - Status
      operationId: ping
      responses:
        200:
          description: 'Server is active.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'OK'

  /health:
    get:
      tags:
        - Status
      operationId: health
      responses:
        200:
          description: 'Microservice general health state reported.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  database:
                    type: string
                    example: 'UP'
