name: CI
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm run test
            - uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
            - name: Run ESLint
              run: npm run lint
